allowBuilds:
  "@google/genai": false
  esbuild: true
  koffi: false
  onnxruntime-node: false
  protobufjs: false
  sharp: false

minimumReleaseAgeExclude:
  - "@agntn/ox@0.1.0"

packages:
  - packages/*
