name: Publish

permissions:
  contents: read
  id-token: write

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: voidzero-dev/setup-vp@24d870228786dc83ae73482406bdd1e7befaec14 # v1.21.0
        with:
          node-version: 26
          registry-url: https://registry.npmjs.org
          cache: true

      - run: vp test

      - run: vp pm publish --no-git-checks
